-- Net-Trade Hungary – demó adatok

INSERT INTO categories (slug, name, icon) VALUES
('raklapok',         'Raklapok',            'pallet'),
('ladak-csomagolas', 'Ládák és csomagolás', 'crate'),
('fureszaru',        'Fűrészáru',           'lumber'),
('tuzifa',           'Tűzifa',              'firewood'),
('teglak',           'BRITTERM téglák',     'brick');

INSERT INTO products (category_id, slug, name, short, description, price, unit, image, stock, featured) VALUES
((SELECT id FROM categories WHERE slug='raklapok'), 'eur-raklap-epal', 'EUR (EPAL) raklap', 'Szabványos 1200×800 mm EUR raklap, EPAL minőségben.', 'Szabványos 1200×800 mm-es EUR raklap, EPAL előírásoknak megfelelő kivitelben, hőkezelt (ISPM-15 / IPPC jelöléssel kérhető) faanyagból. Az ár tájékoztató jellegű, nettó / darab.', 4990, 'db', 'pallet.svg', 100, 1),
((SELECT id FROM categories WHERE slug='raklapok'), 'egyutas-raklap', 'Egyutas raklap', 'Költséghatékony egyutas raklap egyszeri szállításhoz.', 'Könnyűszerkezetes egyutas raklap egyszeri kiszállításokhoz és exporthoz, ahol nincs szükség visszáru-kezelésre. Több méretben gyártjuk. Az ár tájékoztató jellegű, nettó / darab.', 2490, 'db', 'pallet.svg', 100, 0),
((SELECT id FROM categories WHERE slug='raklapok'), 'egyedi-meretu-raklap', 'Egyedi méretű raklap', 'Méretre gyártott raklap a termék pontos paramétereihez.', 'A megrendelő terméke és terhelése alapján méretre tervezett és gyártott raklap, megerősített kivitelben is. Egyedi igény esetén kérjen ajánlatot. Az ár tájékoztató jellegű, nettó / darab.', 3990, 'db', 'pallet.svg', 100, 1),
((SELECT id FROM categories WHERE slug='ladak-csomagolas'), 'exportlada-retegelt', 'Exportláda (rétegelt lemez)', 'Stabil rétegelt lemez exportláda gépek és alkatrészek szállításához.', 'Méretre gyártott rétegelt lemez exportláda raklaptalppal, gépek és nagy értékű áruk tengeri, légi és közúti szállításához. Igény szerint VCI korrózióvédelemmel. Az ár tájékoztató jellegű, nettó / darab.', 14900, 'db', 'crate.svg', 50, 1),
((SELECT id FROM categories WHERE slug='ladak-csomagolas'), 'falada-deszka', 'Faláda (deszkaláda)', 'Hagyományos deszkaláda nehéz és terjedelmes áruhoz.', 'Tömör fűrészáruból készült deszkaláda nehéz, terjedelmes vagy szabálytalan formájú áruk csomagolásához. Hőkezelt faanyagból, ISPM-15 jelöléssel is kérhető. Az ár tájékoztató jellegű, nettó / darab.', 9900, 'db', 'crate.svg', 50, 0),
((SELECT id FROM categories WHERE slug='fureszaru'), 'fenyo-fureszaru-gerenda', 'Fenyő fűrészáru – gerenda', 'Szlovák fenyő gerenda, folyamatos, minőségi alapanyagból.', 'Szlovák fűrészüzemekből származó fenyő gerenda tetőszerkezetekhez, ácsmunkákhoz, építkezéshez. Viszonteladói és projektmennyiség 1–1,5 héten belül. Az ár tájékoztató jellegű, nettó / m³.', 145000, 'm³', 'lumber.svg', 200, 1),
((SELECT id FROM categories WHERE slug='fureszaru'), 'fenyo-pallo-deszka', 'Fenyő palló és deszka', 'Fenyő palló és deszka több méretben, nagykereskedelmi áron.', 'Fenyő palló és deszka különböző vastagságban és hosszban, közel 30 év fakereskedelmi tapasztalattal. Folyamatos, minőség-ellenőrzött szlovák alapanyag. Az ár tájékoztató jellegű, nettó / m³.', 138000, 'm³', 'lumber.svg', 200, 0),
((SELECT id FROM categories WHERE slug='fureszaru'), 'tetolec-fenyo', 'Fenyő tetőléc', 'Szabványos fenyő tetőléc tetőfedéshez.', 'Egészséges, jól szárított fenyő tetőléc tetőfedéshez és állványozáshoz, több méretben, nagy mennyiségben is. Az ár tájékoztató jellegű, nettó / folyóméter.', 320, 'fm', 'lumber.svg', 5000, 0),
((SELECT id FROM categories WHERE slug='tuzifa'), 'hasitott-tuzifa-kemenyfa', 'Hasított tűzifa (keményfa)', 'Vegyes keményfa hasított tűzifa, kiszállítással.', 'Vegyes keményfa (tölgy, bükk, gyertyán) hasított tűzifa, kívánságra konyhakészre vágva, kiváló fűtőértékkel, igény szerint kiszállítással. Az ár tájékoztató jellegű, nettó / m³.', 32000, 'm³', 'firewood.svg', 300, 1),
((SELECT id FROM categories WHERE slug='tuzifa'), 'fenyo-tuzifa', 'Fenyő tűzifa / melléktermék', 'Fenyő tűzifa a faipari feldolgozás melléktermékéből.', 'A faipari feldolgozás során keletkező fenyő melléktermék tűzifaként – nálunk minden faforgács hasznosul. Gyújtósnak és kazánba egyaránt. Az ár tájékoztató jellegű, nettó / m³.', 21000, 'm³', 'firewood.svg', 300, 0),
((SELECT id FROM categories WHERE slug='teglak'), 'britterm-falazotegla', 'BRITTERM falazótégla', 'Szlovák BRITTERM falazótégla, hivatalos magyar képviselet.', 'A szlovák BRITTERM falazótéglái, melyeket 2017 óta képviselünk Magyarországon. Jó hőszigetelés, pontos méret, kiváló ár-érték arány. Az ár tájékoztató jellegű, nettó / darab.', 280, 'db', 'brick.svg', 10000, 1),
((SELECT id FROM categories WHERE slug='teglak'), 'britterm-kemenytegla', 'BRITTERM kéménytégla', 'BRITTERM kémény- és blokktégla rendszerelemek.', 'BRITTERM kémény- és blokktégla rendszerelemek megbízható minőségben, közvetlenül a gyártótól. Projektmennyiség egyeztetés alapján. Az ár tájékoztató jellegű, nettó / darab.', 420, 'db', 'brick.svg', 10000, 0);
