<?php

/**
 * Fordítások (HU / EN / DE). A *_html végű kulcsok HTML-t tartalmaznak,
 * ezeket a sablonok nem escape-elik. A termék- és kategórianevek az
 * adatrétegben magyarul maradnak.
 */

return [
    'hu' => [
        // Navigáció
        'nav.home' => 'Főoldal',
        'nav.products' => 'Termékek',
        'nav.gallery' => 'Galéria',
        'nav.calculator' => 'Árkalkulátor',
        'nav.about' => 'Rólunk',
        'nav.contact' => 'Kapcsolat',
        'nav.cart' => 'Kosár',
        'nav.theme' => 'Sötét / világos mód',

        // Gombok, általános
        'btn.browse' => 'Termékek böngészése',
        'btn.quote' => 'Ajánlatot kérek',
        'btn.add' => 'Kosárba',
        'btn.all' => 'Összes termék →',
        'btn.more' => 'Tovább →',
        'link.about' => 'Rólunk →',

        // Hero
        'hero.eyebrow' => 'Net-Trade Hungary Kft.',
        'hero.title_html' => 'Ipari csomagolás, <span>raklap és fűrészáru</span> egy kézből',
        'hero.lead' => 'Családi vállalkozásként a csomagolástól a faipari gyártáson át a fuvarozásig kísérjük végig partnereinket. „Az ügyfél sikere a mi sikerünk.”',
        'hero.usp1' => '100% minőségi garancia',
        'hero.usp2' => 'Közel 30 év tapasztalat',
        'hero.usp3' => 'Saját fuvarozás',

        // Főoldal szekciók
        'home.activities' => 'Tevékenységeink',
        'home.range' => 'Termékkínálatunk',
        'home.featured' => 'Kiemelt termékek',

        // Szolgáltatások
        'svc.packaging.title' => 'Ipari csomagolás',
        'svc.packaging.text' => 'Gépek, gyártósorok és nagy értékű áruk feladatra szabott csomagolása légi, tengeri és közúti szállításhoz – igény szerint RAPID expressz kivitelezéssel.',
        'svc.woodwork.title' => 'Faipari gyártás',
        'svc.woodwork.text' => 'Egyedi raklapok, exportládák, ömlesztett fatermékek és speciális faszerkezetek gyártása – kizárólag fenntartható forrásból származó alapanyagból.',
        'svc.freight.title' => 'Nemzetközi fuvarozás',
        'svc.freight.text' => '2021 óta saját nyergesvontatóval végzünk közúti fuvarozást – akár a saját logisztikánkhoz, akár megbízásból, több országba.',
        'svc.brick.title' => 'BRITTERM tégla képviselet',
        'svc.brick.text' => '2017 óta a szlovák BRITTERM téglagyártó magyarországi képviselője vagyunk – minőségi falazó-, kémény- és blokktéglák kedvező áron.',
        'svc.lumber.title' => 'Fűrészáru és tűzifa',
        'svc.lumber.text' => 'Közel 30 év tapasztalattal kínálunk minőségi szlovák fenyő fűrészárut és tűzifát nagykereskedelmi mennyiségben, megbízható, folyamatos forrásból.',
        'svc.education.title' => 'Oktatás és képzés',
        'svc.education.text' => 'Családi vállalkozásként a tudás átadása is fontos számunkra: szakmai oktatással és képzésekkel is foglalkozunk.',

        // Értékek
        'val.quality.title' => '100% minőségi garancia',
        'val.quality.text' => 'Minőségi munkát adunk ki a kezünkből; ha mégis hiba lenne, cseréljük vagy javítjuk. Az ügyfél elégedettsége az első.',
        'val.sustain.title' => 'Fenntartható alapanyag',
        'val.sustain.text' => 'Csak felelős, fenntartható forrásból származó faanyaggal dolgozunk, és minden faforgácsot igyekszünk hasznosítani.',
        'val.service.title' => 'Gyors, megbízható kiszolgálás',
        'val.service.text' => 'Viszonteladói és projektrendeléseket jellemzően 1–1,5 héten belül teljesítünk, saját fuvareszközzel is.',

        // Lábléc
        'footer.products' => 'Termékek',
        'footer.info' => 'Információ',
        'footer.contact' => 'Elérhetőség',
        'footer.rights' => 'Minden jog fenntartva.',

        // Rólunk
        'about.lead' => 'A Net-Trade Hungary Kft. családi vállalkozás, amelynek mottója: „Az ügyfél sikere a mi sikerünk.”',
        'about.intro' => 'Vállalkozásunk az ipari csomagolás, a faipari gyártás, a nemzetközi fuvarozás és a kereskedelem területén nyújt komplex, egymásra épülő szolgáltatásokat. Célunk, hogy partnereinket a csomagolástól a kiszállításig egy kézből, megbízhatóan szolgáljuk ki.',
        'about.h_pack' => 'Ipari csomagolás',
        'about.p_pack' => 'Gépek, gyártósorok és nagy értékű áruk feladatra szabott csomagolását vállaljuk légi, tengeri és közúti szállításhoz. Sürgős esetben RAPID expressz csomagolási szolgáltatással is állunk partnereink rendelkezésére.',
        'about.h_wood' => 'Faipari tevékenység',
        'about.p_wood' => 'A fa a szenvedélyünk: egyedi raklapokat, exportládákat, ömlesztett fatermékeket és speciális faszerkezeteket gyártunk. Fontos elvünk, hogy minden faforgács hasznosuljon, és kizárólag fenntartható forrásból származó alapanyaggal dolgozunk.',
        'about.h_freight' => 'Nemzetközi fuvarozás',
        'about.p_freight' => 'Tevékenységünket 2021-ben saját nyergesvontatóval bővítettük, így a közúti fuvarozást akár a saját logisztikánkhoz, akár megbízásból, harmadik fél számára is el tudjuk látni.',
        'about.h_brick' => 'BRITTERM tégla képviselet',
        'about.p_brick' => '2017 óta a szlovák BRITTERM téglagyártó magyarországi képviselői vagyunk. Motivált csapatunk és a kiváló termékek garantálják az elégedett ügyfeleket.',
        'about.h_lumber' => 'Fűrészáru- és tűzifa-kereskedelem',
        'about.p_lumber' => 'Közel 30 év tapasztalattal kereskedünk fenyő fűrészáruval. Megbízható, folyamatos és minőség-ellenőrzött szlovák forrásból dolgozunk; a viszonteladói és projektmennyiségeket jellemzően 1–1,5 héten belül teljesítjük.',
        'about.closing' => 'Mindezt 100%-os minőségi garanciával: ha bármi nem felelne meg, cseréljük vagy javítjuk. Az ügyfél elégedettsége számunkra az első.',
        'stat.experience' => 'fakereskedelmi tapasztalat',
        'stat.britterm' => 'BRITTERM képviselet óta',
        'stat.quality' => 'minőségi garancia',
        'stat.delivery' => 'jellemző teljesítés',

        // Kapcsolat
        'contact.subtitle' => 'Kérdése van? Írjon nekünk, és kollégáink hamarosan válaszolnak.',
        'contact.details' => 'Elérhetőségeink',
        'contact.company' => 'Cégnév',
        'contact.email' => 'E-mail',
        'contact.phone' => 'Telefon',
        'contact.address' => 'Cím',
        'contact.hours' => 'Nyitvatartás',
        'contact.staff' => 'Munkatársaink',
        'contact.role_kristof' => 'Vezetés, tervezés, gyártás, fuvarozás',
        'contact.role_laszlo' => 'Kereskedelem, pénzügy, marketing, ügynöki üzletág',
        'contact.role_laszlone' => 'Vezetés, oktatás, pályázatok',
        'form.name' => 'Név',
        'form.email' => 'E-mail',
        'form.subject' => 'Tárgy',
        'form.message' => 'Üzenet',
        'form.send' => 'Üzenet küldése',
        'contact.sent' => 'Köszönjük az üzenetet',
        'contact.sent_after' => '! Hamarosan válaszolunk.',

        // Termékek lista
        'products.subtitle' => 'Böngéssze a teljes kínálatunkat, vagy szűrjön kategóriára.',
        'products.search' => 'Keresés…',
        'products.search_btn' => 'Keresés',
        'products.categories' => 'Kategóriák',
        'products.all' => 'Összes',
        'products.count' => 'termék',
        'products.empty' => 'Nincs a keresésnek megfelelő termék.',
        'products.clear' => 'Szűrők törlése',

        // Galéria
        'gallery.title' => 'Galéria',
        'gallery.subtitle' => 'Pillantás a csomagolásainkba és a gyártott termékeinkbe.',
        'gallery.cap_packaging' => 'Ipari csomagolás',
        'gallery.cap_crate' => 'Exportláda',
        'gallery.cap_pallet' => 'Egyedi raklap',
        'gallery.cap_lumber' => 'Fenyő fűrészáru',
        'gallery.cap_firewood' => 'Tűzifa',
        'gallery.cap_brick' => 'BRITTERM tégla',

        // Kalkulátor
        'calc.title' => 'Árkalkulátor',
        'calc.subtitle' => 'Állítsa össze igényét, és kérjen tájékoztató árat néhány kattintással.',
        'calc.product' => 'Termék',
        'calc.qty' => 'Mennyiség',
        'calc.size' => 'Méret-szorzó',
        'calc.size_std' => 'Szabványos méret',
        'calc.size_large' => 'Nagyobb / megerősített (+30%)',
        'calc.size_xl' => 'Extra nagy / nehéz (+60%)',
        'calc.result' => 'Becsült nettó ár',
        'calc.unit_price' => 'Egységár',
        'calc.note' => 'A megadott ár tájékoztató jellegű, nem minősül ajánlatnak. Pontos árért és egyedi méretekért kérjen ajánlatot.',
        'calc.request' => 'Ajánlatot kérek erre',

        // Kosár / pénztár / egyéb
        'cart.title' => 'Kosár',
        'cart.empty' => 'A kosara jelenleg üres.',
        'cart.start' => 'Vásárlás megkezdése',
        'cart.product' => 'Termék',
        'cart.unit' => 'Egységár',
        'cart.qty' => 'Mennyiség',
        'cart.subtotal' => 'Részösszeg',
        'cart.update' => 'Kosár frissítése',
        'cart.total' => 'Összesen:',
        'cart.checkout' => 'Tovább a pénztárhoz',
        'checkout.title' => 'Pénztár',
        'checkout.billing' => 'Számlázási adatok',
        'checkout.phone' => 'Telefonszám',
        'checkout.zip' => 'Irányítószám',
        'checkout.addr' => 'Cím',
        'checkout.note' => 'Megjegyzés',
        'checkout.submit' => 'Rendelés véglegesítése',
        'checkout.summary' => 'Rendelés összegzése',
        'checkout.total' => 'Összesen',
        'checkout.back' => '← Vissza a kosárhoz',
        'success.title' => 'Köszönjük a rendelést',
        'success.text' => 'Rendelését rögzítettük. Hamarosan e-mailben küldjük a visszaigazolást a részletekkel.',
        'success.continue' => 'Vásárlás folytatása',
        'detail.stock_in' => 'Raktáron',
        'detail.stock_out' => 'Jelenleg nem elérhető',
        'detail.qty' => 'Mennyiség',
        'detail.add' => 'Kosárba teszem',
        'detail.meta1' => '100% minőségi garancia – csere vagy javítás',
        'detail.meta2' => 'Saját nyergesvontatóval is szállítunk',
        'detail.meta3' => 'Egyedi méret és nagy mennyiség egyeztetés alapján',
        'crumb.home' => 'Főoldal',
        'crumb.products' => 'Termékek',
        'e404.title' => 'Az oldal nem található',
        'e404.text' => 'A keresett oldal nem létezik vagy áthelyezésre került.',
        'e404.back' => 'Vissza a főoldalra',

        // Felhasználói menü
        'nav.login' => 'Belépés',
        'nav.register' => 'Regisztráció',
        'nav.logout' => 'Kilépés',
        'nav.admin' => 'Admin',

        // Autentikáció
        'auth.login_title' => 'Belépés',
        'auth.register_title' => 'Regisztráció',
        'auth.name' => 'Név',
        'auth.email' => 'E-mail',
        'auth.password' => 'Jelszó',
        'auth.password2' => 'Jelszó még egyszer',
        'auth.login_btn' => 'Belépés',
        'auth.register_btn' => 'Fiók létrehozása',
        'auth.no_account' => 'Még nincs fiókod?',
        'auth.have_account' => 'Van már fiókod?',
        'auth.login_link' => 'Belépés',
        'auth.register_link' => 'Regisztrálok',
        'auth.first_admin' => 'Te leszel az első felhasználó – automatikusan adminisztrátori jogot kapsz.',
        'auth.err_csrf' => 'Lejárt vagy érvénytelen űrlap. Próbáld újra.',
        'auth.err_db' => 'Az adatbázis nincs beállítva, így a regisztráció/belépés most nem érhető el. Futtasd a telepítőt (lásd README).',
        'auth.err_required' => 'Tölts ki minden kötelező mezőt.',
        'auth.err_email' => 'Adj meg egy érvényes e-mail címet.',
        'auth.err_short' => 'A jelszó legalább 6 karakter legyen.',
        'auth.err_match' => 'A két jelszó nem egyezik.',
        'auth.err_taken' => 'Ezzel az e-mail címmel már létezik fiók.',
        'auth.err_login' => 'Hibás e-mail vagy jelszó.',

        // Admin (belső felület – csak magyarul, a többi nyelv erre esik vissza)
        'admin.title' => 'Admin – termékek',
        'admin.new_product' => 'Új termék',
        'admin.name' => 'Megnevezés',
        'admin.category' => 'Kategória',
        'admin.price' => 'Ár',
        'admin.unit' => 'Mértékegység',
        'admin.stock' => 'Készlet',
        'admin.status' => 'Állapot',
        'admin.short' => 'Rövid leírás',
        'admin.description' => 'Leírás',
        'admin.slug' => 'Slug (URL)',
        'admin.slug_hint' => 'üresen hagyva a névből készül',
        'admin.image' => 'Kép',
        'admin.current_image' => 'Jelenlegi kép',
        'admin.featured' => 'Kiemelt',
        'admin.active' => 'Aktív (látható a boltban)',
        'admin.inactive' => 'inaktív',
        'admin.edit' => 'Szerkesztés',
        'admin.delete' => 'Törlés',
        'admin.confirm_delete' => 'Biztosan törlöd ezt a terméket?',
        'admin.save' => 'Mentés',
        'admin.cancel' => 'Mégse',
        'admin.back' => 'Vissza a listához',
        'admin.created' => 'A termék létrejött.',
        'admin.updated' => 'A termék módosítva.',
        'admin.deleted' => 'A termék törölve.',
        'admin.no_db' => 'Nincs adatbázis-kapcsolat – a módosítások nem menthetők. Futtasd a telepítőt: php database/install.php',
    ],

    'en' => [
        'nav.home' => 'Home',
        'nav.products' => 'Products',
        'nav.gallery' => 'Gallery',
        'nav.calculator' => 'Price calculator',
        'nav.about' => 'About us',
        'nav.contact' => 'Contact',
        'nav.cart' => 'Cart',
        'nav.theme' => 'Dark / light mode',

        'btn.browse' => 'Browse products',
        'btn.quote' => 'Request a quote',
        'btn.add' => 'Add to cart',
        'btn.all' => 'All products →',
        'btn.more' => 'More →',
        'link.about' => 'About us →',

        'hero.eyebrow' => 'Net-Trade Hungary Ltd.',
        'hero.title_html' => 'Industrial packaging, <span>pallets &amp; lumber</span> from one source',
        'hero.lead' => 'As a family business we support our partners from packaging through woodworking to transport. “The client’s success is our success.”',
        'hero.usp1' => '100% quality guarantee',
        'hero.usp2' => 'Nearly 30 years of experience',
        'hero.usp3' => 'Own freight transport',

        'home.activities' => 'What we do',
        'home.range' => 'Our product range',
        'home.featured' => 'Featured products',

        'svc.packaging.title' => 'Industrial packaging',
        'svc.packaging.text' => 'Task-specific packaging of machines, production lines and high-value goods for air, sea and road transport – with RAPID express service on request.',
        'svc.woodwork.title' => 'Woodworking',
        'svc.woodwork.text' => 'Manufacturing of custom pallets, export crates, bulk wood products and special wooden structures – exclusively from sustainably sourced material.',
        'svc.freight.title' => 'International freight',
        'svc.freight.text' => 'Since 2021 we run road transport with our own articulated truck – for our own logistics or as a third-party service, across several countries.',
        'svc.brick.title' => 'BRITTERM brick agency',
        'svc.brick.text' => 'Since 2017 we are the Hungarian representative of the Slovak brick maker BRITTERM – quality wall, chimney and block bricks at fair prices.',
        'svc.lumber.title' => 'Lumber & firewood',
        'svc.lumber.text' => 'With nearly 30 years of experience we offer quality Slovak pine lumber and firewood in wholesale quantities from a reliable, continuous source.',
        'svc.education.title' => 'Education & training',
        'svc.education.text' => 'As a family business, passing on knowledge matters to us: we also provide professional education and training.',

        'val.quality.title' => '100% quality guarantee',
        'val.quality.text' => 'We deliver quality work; should anything be faulty, we replace or repair it. Client satisfaction comes first.',
        'val.sustain.title' => 'Sustainable material',
        'val.sustain.text' => 'We only work with wood from responsible, sustainable sources, and we aim to make use of every wood chip.',
        'val.service.title' => 'Fast, reliable service',
        'val.service.text' => 'Reseller and project orders are typically fulfilled within 1–1.5 weeks, with our own transport too.',

        'footer.products' => 'Products',
        'footer.info' => 'Information',
        'footer.contact' => 'Contact',
        'footer.rights' => 'All rights reserved.',

        'about.lead' => 'Net-Trade Hungary Ltd. is a family business whose motto is: “The client’s success is our success.”',
        'about.intro' => 'Our company offers complex, interlocking services in industrial packaging, woodworking, international freight and trade. Our goal is to serve partners reliably, from packaging to delivery, from a single source.',
        'about.h_pack' => 'Industrial packaging',
        'about.p_pack' => 'We provide task-specific packaging of machines, production lines and high-value goods for air, sea and road transport. For urgent cases our RAPID express packaging service is also available.',
        'about.h_wood' => 'Woodworking',
        'about.p_wood' => 'Wood is our passion: we make custom pallets, export crates, bulk wood products and special wooden structures. We make use of every wood chip and work exclusively with sustainably sourced material.',
        'about.h_freight' => 'International freight',
        'about.p_freight' => 'In 2021 we expanded with our own articulated truck, so we can handle road transport for our own logistics or for third parties on commission.',
        'about.h_brick' => 'BRITTERM brick agency',
        'about.p_brick' => 'Since 2017 we are the Hungarian representatives of the Slovak brick maker BRITTERM. Our motivated team and excellent products guarantee satisfied customers.',
        'about.h_lumber' => 'Lumber & firewood trade',
        'about.p_lumber' => 'We have traded pine lumber for nearly 30 years, working from a reliable, continuous and quality-checked Slovak source; reseller and project quantities are usually fulfilled within 1–1.5 weeks.',
        'about.closing' => 'All of this with a 100% quality guarantee: if anything is not right, we replace or repair it. Client satisfaction comes first.',
        'stat.experience' => 'years in lumber trade',
        'stat.britterm' => 'BRITTERM agency since',
        'stat.quality' => 'quality guarantee',
        'stat.delivery' => 'typical fulfilment',

        'contact.subtitle' => 'Have a question? Write to us and our colleagues will reply shortly.',
        'contact.details' => 'Our contact details',
        'contact.company' => 'Company',
        'contact.email' => 'Email',
        'contact.phone' => 'Phone',
        'contact.address' => 'Address',
        'contact.hours' => 'Opening hours',
        'contact.staff' => 'Our team',
        'contact.role_kristof' => 'Management, planning, manufacturing, transport',
        'contact.role_laszlo' => 'Trade, finance, marketing, agency business',
        'contact.role_laszlone' => 'Management, education, grant applications',
        'form.name' => 'Name',
        'form.email' => 'Email',
        'form.subject' => 'Subject',
        'form.message' => 'Message',
        'form.send' => 'Send message',
        'contact.sent' => 'Thank you for your message',
        'contact.sent_after' => '! We will reply soon.',

        'products.subtitle' => 'Browse our full range or filter by category.',
        'products.search' => 'Search…',
        'products.search_btn' => 'Search',
        'products.categories' => 'Categories',
        'products.all' => 'All',
        'products.count' => 'products',
        'products.empty' => 'No products match your search.',
        'products.clear' => 'Clear filters',

        'gallery.title' => 'Gallery',
        'gallery.subtitle' => 'A glimpse into our packaging and manufactured products.',
        'gallery.cap_packaging' => 'Industrial packaging',
        'gallery.cap_crate' => 'Export crate',
        'gallery.cap_pallet' => 'Custom pallet',
        'gallery.cap_lumber' => 'Pine lumber',
        'gallery.cap_firewood' => 'Firewood',
        'gallery.cap_brick' => 'BRITTERM brick',

        'calc.title' => 'Price calculator',
        'calc.subtitle' => 'Put together your needs and get an indicative price in a few clicks.',
        'calc.product' => 'Product',
        'calc.qty' => 'Quantity',
        'calc.size' => 'Size factor',
        'calc.size_std' => 'Standard size',
        'calc.size_large' => 'Larger / reinforced (+30%)',
        'calc.size_xl' => 'Extra large / heavy (+60%)',
        'calc.result' => 'Estimated net price',
        'calc.unit_price' => 'Unit price',
        'calc.note' => 'The price shown is indicative only and is not an offer. For an exact price and custom sizes, please request a quote.',
        'calc.request' => 'Request a quote for this',

        'cart.title' => 'Cart',
        'cart.empty' => 'Your cart is currently empty.',
        'cart.start' => 'Start shopping',
        'cart.product' => 'Product',
        'cart.unit' => 'Unit price',
        'cart.qty' => 'Quantity',
        'cart.subtotal' => 'Subtotal',
        'cart.update' => 'Update cart',
        'cart.total' => 'Total:',
        'cart.checkout' => 'Proceed to checkout',
        'checkout.title' => 'Checkout',
        'checkout.billing' => 'Billing details',
        'checkout.phone' => 'Phone number',
        'checkout.zip' => 'Postal code',
        'checkout.addr' => 'Address',
        'checkout.note' => 'Note',
        'checkout.submit' => 'Place order',
        'checkout.summary' => 'Order summary',
        'checkout.total' => 'Total',
        'checkout.back' => '← Back to cart',
        'success.title' => 'Thank you for your order',
        'success.text' => 'Your order has been recorded. We will send an email confirmation with the details shortly.',
        'success.continue' => 'Continue shopping',
        'detail.stock_in' => 'In stock',
        'detail.stock_out' => 'Currently unavailable',
        'detail.qty' => 'Quantity',
        'detail.add' => 'Add to cart',
        'detail.meta1' => '100% quality guarantee – replacement or repair',
        'detail.meta2' => 'We also deliver with our own truck',
        'detail.meta3' => 'Custom size and large quantity by arrangement',
        'crumb.home' => 'Home',
        'crumb.products' => 'Products',
        'e404.title' => 'Page not found',
        'e404.text' => 'The page you are looking for does not exist or has been moved.',
        'e404.back' => 'Back to home',

        'nav.login' => 'Sign in',
        'nav.register' => 'Sign up',
        'nav.logout' => 'Sign out',
        'nav.admin' => 'Admin',

        'auth.login_title' => 'Sign in',
        'auth.register_title' => 'Create account',
        'auth.name' => 'Name',
        'auth.email' => 'Email',
        'auth.password' => 'Password',
        'auth.password2' => 'Repeat password',
        'auth.login_btn' => 'Sign in',
        'auth.register_btn' => 'Create account',
        'auth.no_account' => 'No account yet?',
        'auth.have_account' => 'Already have an account?',
        'auth.login_link' => 'Sign in',
        'auth.register_link' => 'Sign up',
        'auth.first_admin' => 'You will be the first user – you will automatically get administrator rights.',
        'auth.err_csrf' => 'Expired or invalid form. Please try again.',
        'auth.err_db' => 'The database is not set up, so sign in / sign up is currently unavailable. Run the installer (see README).',
        'auth.err_required' => 'Please fill in all required fields.',
        'auth.err_email' => 'Please enter a valid email address.',
        'auth.err_short' => 'The password must be at least 6 characters.',
        'auth.err_match' => 'The two passwords do not match.',
        'auth.err_taken' => 'An account with this email already exists.',
        'auth.err_login' => 'Incorrect email or password.',
    ],

    'de' => [
        'nav.home' => 'Startseite',
        'nav.products' => 'Produkte',
        'nav.gallery' => 'Galerie',
        'nav.calculator' => 'Preisrechner',
        'nav.about' => 'Über uns',
        'nav.contact' => 'Kontakt',
        'nav.cart' => 'Warenkorb',
        'nav.theme' => 'Dunkel- / Hellmodus',

        'btn.browse' => 'Produkte ansehen',
        'btn.quote' => 'Angebot anfordern',
        'btn.add' => 'In den Warenkorb',
        'btn.all' => 'Alle Produkte →',
        'btn.more' => 'Mehr →',
        'link.about' => 'Über uns →',

        'hero.eyebrow' => 'Net-Trade Hungary GmbH',
        'hero.title_html' => 'Industrieverpackung, <span>Paletten &amp; Schnittholz</span> aus einer Hand',
        'hero.lead' => 'Als Familienunternehmen begleiten wir unsere Partner von der Verpackung über die Holzverarbeitung bis zum Transport. „Der Erfolg des Kunden ist unser Erfolg.“',
        'hero.usp1' => '100% Qualitätsgarantie',
        'hero.usp2' => 'Fast 30 Jahre Erfahrung',
        'hero.usp3' => 'Eigener Fuhrpark',

        'home.activities' => 'Unsere Tätigkeiten',
        'home.range' => 'Unser Sortiment',
        'home.featured' => 'Ausgewählte Produkte',

        'svc.packaging.title' => 'Industrieverpackung',
        'svc.packaging.text' => 'Aufgabenspezifische Verpackung von Maschinen, Fertigungslinien und hochwertigen Gütern für Luft-, See- und Straßentransport – auf Wunsch mit RAPID-Expressservice.',
        'svc.woodwork.title' => 'Holzverarbeitung',
        'svc.woodwork.text' => 'Herstellung von individuellen Paletten, Exportkisten, Holz-Schüttgut und speziellen Holzkonstruktionen – ausschließlich aus nachhaltig bezogenem Material.',
        'svc.freight.title' => 'Internationaler Transport',
        'svc.freight.text' => 'Seit 2021 betreiben wir den Straßentransport mit eigenem Sattelzug – für die eigene Logistik oder als Dienstleistung für Dritte, in mehreren Ländern.',
        'svc.brick.title' => 'BRITTERM Ziegelvertretung',
        'svc.brick.text' => 'Seit 2017 sind wir die ungarische Vertretung des slowakischen Ziegelherstellers BRITTERM – hochwertige Mauer-, Schornstein- und Blockziegel zu fairen Preisen.',
        'svc.lumber.title' => 'Schnittholz & Brennholz',
        'svc.lumber.text' => 'Mit fast 30 Jahren Erfahrung bieten wir hochwertiges slowakisches Kiefernschnittholz und Brennholz in Großhandelsmengen aus zuverlässiger, kontinuierlicher Quelle.',
        'svc.education.title' => 'Aus- und Weiterbildung',
        'svc.education.text' => 'Als Familienunternehmen ist uns die Wissensvermittlung wichtig: Wir bieten auch fachliche Aus- und Weiterbildung an.',

        'val.quality.title' => '100% Qualitätsgarantie',
        'val.quality.text' => 'Wir liefern Qualitätsarbeit; sollte etwas mangelhaft sein, ersetzen oder reparieren wir es. Die Zufriedenheit des Kunden steht an erster Stelle.',
        'val.sustain.title' => 'Nachhaltiges Material',
        'val.sustain.text' => 'Wir arbeiten nur mit Holz aus verantwortungsvollen, nachhaltigen Quellen und nutzen möglichst jeden Holzspan.',
        'val.service.title' => 'Schneller, zuverlässiger Service',
        'val.service.text' => 'Händler- und Projektbestellungen erfüllen wir in der Regel innerhalb von 1–1,5 Wochen, auch mit eigenem Transport.',

        'footer.products' => 'Produkte',
        'footer.info' => 'Information',
        'footer.contact' => 'Kontakt',
        'footer.rights' => 'Alle Rechte vorbehalten.',

        'about.lead' => 'Die Net-Trade Hungary GmbH ist ein Familienunternehmen mit dem Motto: „Der Erfolg des Kunden ist unser Erfolg.“',
        'about.intro' => 'Unser Unternehmen bietet komplexe, aufeinander aufbauende Dienstleistungen in den Bereichen Industrieverpackung, Holzverarbeitung, internationaler Transport und Handel. Unser Ziel ist es, Partner von der Verpackung bis zur Lieferung zuverlässig aus einer Hand zu bedienen.',
        'about.h_pack' => 'Industrieverpackung',
        'about.p_pack' => 'Wir übernehmen die aufgabenspezifische Verpackung von Maschinen, Fertigungslinien und hochwertigen Gütern für Luft-, See- und Straßentransport. In dringenden Fällen steht auch unser RAPID-Expressservice zur Verfügung.',
        'about.h_wood' => 'Holzverarbeitung',
        'about.p_wood' => 'Holz ist unsere Leidenschaft: Wir fertigen individuelle Paletten, Exportkisten, Holz-Schüttgut und spezielle Holzkonstruktionen. Wir nutzen jeden Holzspan und arbeiten ausschließlich mit nachhaltig bezogenem Material.',
        'about.h_freight' => 'Internationaler Transport',
        'about.p_freight' => '2021 haben wir mit einem eigenen Sattelzug erweitert, sodass wir den Straßentransport für die eigene Logistik oder im Auftrag Dritter abwickeln können.',
        'about.h_brick' => 'BRITTERM Ziegelvertretung',
        'about.p_brick' => 'Seit 2017 sind wir die ungarische Vertretung des slowakischen Ziegelherstellers BRITTERM. Unser motiviertes Team und die hervorragenden Produkte sorgen für zufriedene Kunden.',
        'about.h_lumber' => 'Schnittholz- und Brennholzhandel',
        'about.p_lumber' => 'Wir handeln seit fast 30 Jahren mit Kiefernschnittholz aus zuverlässiger, kontinuierlicher und qualitätsgeprüfter slowakischer Quelle; Händler- und Projektmengen erfüllen wir meist innerhalb von 1–1,5 Wochen.',
        'about.closing' => 'All dies mit 100% Qualitätsgarantie: Wenn etwas nicht stimmt, ersetzen oder reparieren wir es. Die Zufriedenheit des Kunden steht für uns an erster Stelle.',
        'stat.experience' => 'Jahre im Holzhandel',
        'stat.britterm' => 'BRITTERM-Vertretung seit',
        'stat.quality' => 'Qualitätsgarantie',
        'stat.delivery' => 'typische Erfüllung',

        'contact.subtitle' => 'Haben Sie eine Frage? Schreiben Sie uns, unsere Kollegen antworten in Kürze.',
        'contact.details' => 'Unsere Kontaktdaten',
        'contact.company' => 'Firma',
        'contact.email' => 'E-Mail',
        'contact.phone' => 'Telefon',
        'contact.address' => 'Adresse',
        'contact.hours' => 'Öffnungszeiten',
        'contact.staff' => 'Unser Team',
        'contact.role_kristof' => 'Leitung, Planung, Fertigung, Transport',
        'contact.role_laszlo' => 'Handel, Finanzen, Marketing, Vertretungsgeschäft',
        'contact.role_laszlone' => 'Leitung, Bildung, Förderanträge',
        'form.name' => 'Name',
        'form.email' => 'E-Mail',
        'form.subject' => 'Betreff',
        'form.message' => 'Nachricht',
        'form.send' => 'Nachricht senden',
        'contact.sent' => 'Vielen Dank für Ihre Nachricht',
        'contact.sent_after' => '! Wir antworten in Kürze.',

        'products.subtitle' => 'Durchstöbern Sie unser gesamtes Sortiment oder filtern Sie nach Kategorie.',
        'products.search' => 'Suche…',
        'products.search_btn' => 'Suchen',
        'products.categories' => 'Kategorien',
        'products.all' => 'Alle',
        'products.count' => 'Produkte',
        'products.empty' => 'Keine Produkte entsprechen Ihrer Suche.',
        'products.clear' => 'Filter zurücksetzen',

        'gallery.title' => 'Galerie',
        'gallery.subtitle' => 'Ein Einblick in unsere Verpackungen und gefertigten Produkte.',
        'gallery.cap_packaging' => 'Industrieverpackung',
        'gallery.cap_crate' => 'Exportkiste',
        'gallery.cap_pallet' => 'Individuelle Palette',
        'gallery.cap_lumber' => 'Kiefernschnittholz',
        'gallery.cap_firewood' => 'Brennholz',
        'gallery.cap_brick' => 'BRITTERM Ziegel',

        'calc.title' => 'Preisrechner',
        'calc.subtitle' => 'Stellen Sie Ihren Bedarf zusammen und erhalten Sie in wenigen Klicks einen Richtpreis.',
        'calc.product' => 'Produkt',
        'calc.qty' => 'Menge',
        'calc.size' => 'Größenfaktor',
        'calc.size_std' => 'Standardgröße',
        'calc.size_large' => 'Größer / verstärkt (+30%)',
        'calc.size_xl' => 'Extra groß / schwer (+60%)',
        'calc.result' => 'Geschätzter Nettopreis',
        'calc.unit_price' => 'Einzelpreis',
        'calc.note' => 'Der angezeigte Preis ist unverbindlich und stellt kein Angebot dar. Für einen genauen Preis und Sondermaße fordern Sie bitte ein Angebot an.',
        'calc.request' => 'Dafür ein Angebot anfordern',

        'cart.title' => 'Warenkorb',
        'cart.empty' => 'Ihr Warenkorb ist derzeit leer.',
        'cart.start' => 'Einkauf beginnen',
        'cart.product' => 'Produkt',
        'cart.unit' => 'Einzelpreis',
        'cart.qty' => 'Menge',
        'cart.subtotal' => 'Zwischensumme',
        'cart.update' => 'Warenkorb aktualisieren',
        'cart.total' => 'Gesamt:',
        'cart.checkout' => 'Zur Kasse',
        'checkout.title' => 'Kasse',
        'checkout.billing' => 'Rechnungsdaten',
        'checkout.phone' => 'Telefonnummer',
        'checkout.zip' => 'Postleitzahl',
        'checkout.addr' => 'Adresse',
        'checkout.note' => 'Anmerkung',
        'checkout.submit' => 'Bestellung abschließen',
        'checkout.summary' => 'Bestellübersicht',
        'checkout.total' => 'Gesamt',
        'checkout.back' => '← Zurück zum Warenkorb',
        'success.title' => 'Vielen Dank für Ihre Bestellung',
        'success.text' => 'Ihre Bestellung wurde erfasst. Wir senden Ihnen in Kürze eine Bestätigung mit den Details per E-Mail.',
        'success.continue' => 'Weiter einkaufen',
        'detail.stock_in' => 'Auf Lager',
        'detail.stock_out' => 'Derzeit nicht verfügbar',
        'detail.qty' => 'Menge',
        'detail.add' => 'In den Warenkorb',
        'detail.meta1' => '100% Qualitätsgarantie – Ersatz oder Reparatur',
        'detail.meta2' => 'Wir liefern auch mit eigenem Sattelzug',
        'detail.meta3' => 'Sondermaße und große Mengen nach Absprache',
        'crumb.home' => 'Startseite',
        'crumb.products' => 'Produkte',
        'e404.title' => 'Seite nicht gefunden',
        'e404.text' => 'Die gesuchte Seite existiert nicht oder wurde verschoben.',
        'e404.back' => 'Zurück zur Startseite',

        'nav.login' => 'Anmelden',
        'nav.register' => 'Registrieren',
        'nav.logout' => 'Abmelden',
        'nav.admin' => 'Admin',

        'auth.login_title' => 'Anmelden',
        'auth.register_title' => 'Konto erstellen',
        'auth.name' => 'Name',
        'auth.email' => 'E-Mail',
        'auth.password' => 'Passwort',
        'auth.password2' => 'Passwort wiederholen',
        'auth.login_btn' => 'Anmelden',
        'auth.register_btn' => 'Konto erstellen',
        'auth.no_account' => 'Noch kein Konto?',
        'auth.have_account' => 'Schon ein Konto?',
        'auth.login_link' => 'Anmelden',
        'auth.register_link' => 'Registrieren',
        'auth.first_admin' => 'Sie sind der erste Benutzer – Sie erhalten automatisch Administratorrechte.',
        'auth.err_csrf' => 'Abgelaufenes oder ungültiges Formular. Bitte erneut versuchen.',
        'auth.err_db' => 'Die Datenbank ist nicht eingerichtet, daher sind An-/Abmeldung derzeit nicht verfügbar. Führen Sie das Installationsskript aus (siehe README).',
        'auth.err_required' => 'Bitte füllen Sie alle Pflichtfelder aus.',
        'auth.err_email' => 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
        'auth.err_short' => 'Das Passwort muss mindestens 6 Zeichen lang sein.',
        'auth.err_match' => 'Die beiden Passwörter stimmen nicht überein.',
        'auth.err_taken' => 'Mit dieser E-Mail existiert bereits ein Konto.',
        'auth.err_login' => 'Falsche E-Mail oder falsches Passwort.',
    ],
];
